FROM python:3.6-alpine
RUN apk add --update build-base libffi-dev zlib-dev
RUN apk add --update postgresql-dev
RUN pip install gunicorn google-python-cloud-debugger
ADD . /code
WORKDIR /code
RUN pip install -r requirements.txt
CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 languages:app
