"""Initial schema

Revision ID: 82923d6336a8
Revises: 
Create Date: 2025-12-05 22:40:59.204443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82923d6336a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('locale', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('local_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('locale')
    )
    op.create_table('language_packs',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('firmware_major', sa.Integer(), nullable=False),
    sa.Column('firmware_minor', sa.Integer(), nullable=False),
    sa.Column('firmware_patch', sa.Integer(), nullable=False),
    sa.Column('hardware', sa.String(), nullable=False),
    sa.Column('language_id', sa.String(length=12), nullable=False),
    sa.Column('file', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['languages.locale'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_packs_language_id'), 'language_packs', ['language_id'], unique=False)
    op.create_index('language_pack_firmware_hardware_languageid', 'language_packs', ['firmware_major', 'firmware_minor', 'firmware_patch', 'hardware', 'language_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('language_pack_firmware_hardware_languageid', table_name='language_packs')
    op.drop_index(op.f('ix_language_packs_language_id'), table_name='language_packs')
    op.drop_table('language_packs')
    op.drop_table('languages')
    # ### end Alembic commands ###
